create table if not exists users (
  uid integer primary key,
  name varchar unique not null,
  password varchar not null
);

create table if not exists key_pairs (
  id integer primary key generated by default as identity,
  private_key varchar not null,
  public_key varchar not null,
  created_at bigint not null,
  created_at_timezone integer not null,
  is_active boolean default true
);

create table if not exists jwt_tokens (
  jti varchar(36) primary key,
  uid integer not null references users(uid),
  created_at bigint not null,
  created_at_timezone integer default 0,
  expires_at bigint not null,
  jwt_token varchar not null,
  is_revoked boolean default false not null,
  revoked_at bigint
);
